# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField()),
                ('pick_up_address', models.CharField(max_length=200)),
                ('pick_up_companty_name', models.CharField(max_length=300)),
                ('pick_up_unit_number', models.CharField(max_length=300)),
                ('pick_up_lon', models.FloatField()),
                ('pick_up_lat', models.FloatField()),
                ('delivery_address', models.CharField(max_length=300)),
                ('delivery_companty_name', models.CharField(max_length=300)),
                ('dilivery_unit_number', models.CharField(max_length=300)),
                ('delivery_lon', models.FloatField()),
                ('delivery_lat', models.FloatField()),
                ('back_to_pick_up_address', models.CharField(max_length=300)),
                ('back_lon', models.FloatField()),
                ('back_lat', models.FloatField()),
                ('imstructions', models.CharField(max_length=300)),
                ('return_to', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=300)),
                ('favorites', models.BooleanField()),
                ('delivery_status', models.CharField(max_length=300)),
                ('driver', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('arrange_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('weight', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('arrange_id', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=b'')),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('is_client', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('token', models.CharField(max_length=300)),
                ('restore', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='parcel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Parcel'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
